#ifndef __LOGHELPER_H_
#define __LOGHELPER_H_

#define DEFAULT_LOGGER_CONFIG "<<DEFAULT_CONFIG>>"
#define DEFAULT_LOGGER_DATA "<<NEVER SHOULD SEE THIS - UNINITIALIZED DATA!>>"
#define LOGGER_KILL_COMMAND "LoggerlibKill"

#endif //__LOGHELPER_H_
